dataset_name: 'custom'
outpout_dir: results/
prediction_dir: training_prediction/
threshold: 0.5
alpha: 0.5 #weight of loss for multi training training
loss: "Dice" #BCE
gpu_device: 1
lr: 0.5e-4
batch_size: 64
epochs: 100
workers: 8 
seed: 123
log_dir : log/
tbp: 8888
# model_architecture: ['Unet', 'UnetPlusPlus','MAnet','Linknet']
model_architecture: ['DeepLabV3','DeepLabV3Plus','FPN','PSPNet','PAN']

encoder_name: ['resnet18',
 'resnet34',
 'resnet50',
 'resnet101',
 'resnet152',
 'resnext50_32x4d',
 'resnext101_32x8d',
 'vgg11',
 'vgg11_bn',
 'vgg13',
 'vgg13_bn',
 'vgg16',
 'vgg16_bn',
 'vgg19',
 'vgg19_bn',
 'efficientnet-b0',
 'efficientnet-b1',
 'efficientnet-b2',
 'efficientnet-b3',
 'efficientnet-b4',
 'efficientnet-b5',
 'efficientnet-b6',
 'efficientnet-b7',
 'mobilenet_v2',
 'timm-efficientnet-b0',
 'timm-efficientnet-b1',
 'timm-efficientnet-b2',
 'timm-efficientnet-b3',
 'timm-efficientnet-b4',
 'timm-efficientnet-b5',
 'timm-efficientnet-b6',
 'timm-efficientnet-b7',
 'timm-efficientnet-b8',
 'timm-tf_efficientnet_lite0',
 'timm-tf_efficientnet_lite1',
 'timm-tf_efficientnet_lite2',
 'timm-tf_efficientnet_lite3',
 'timm-tf_efficientnet_lite4',
 'timm-resnest14d',
 'timm-resnest26d',
 'timm-resnest50d',
 'timm-resnest101e',
 'timm-resnest200e',
 'timm-resnest269e',
 'timm-resnest50d_4s2x40d',
 'timm-resnest50d_1s4x24d',
 'timm-res2net50_26w_4s',
 'timm-res2net101_26w_4s',
 'timm-res2net50_26w_6s',
 'timm-res2net50_26w_8s',
 'timm-res2net50_48w_2s',
 'timm-res2net50_14w_8s',
 'timm-res2next50',
 'timm-regnetx_002',
 'timm-regnetx_004',
 'timm-regnetx_006',
 'timm-regnetx_008',
 'timm-regnetx_016',
 'timm-regnetx_032',
 'timm-regnetx_040',
 'timm-regnetx_064',
 'timm-regnetx_080',
 'timm-regnetx_120',
 'timm-regnetx_160',
 'timm-regnetx_320',
 'timm-regnety_002',
 'timm-regnety_004',
 'timm-regnety_006',
 'timm-regnety_008',
 'timm-regnety_016',
 'timm-regnety_032',
 'timm-regnety_040',
 'timm-regnety_064',
 'timm-regnety_080',
 'timm-regnety_120',
 'timm-regnety_160',
 'timm-regnety_320',
 'timm-mobilenetv3_large_075',
 'timm-mobilenetv3_large_100',
 'timm-mobilenetv3_large_minimal_100',
 'timm-mobilenetv3_small_075',
 'timm-mobilenetv3_small_100',
 'timm-mobilenetv3_small_minimal_100',
 'timm-gernet_s',
 'timm-gernet_m',
 'timm-gernet_l',
 'mobileone_s0',
 'mobileone_s1',
 'mobileone_s2',
 'mobileone_s3',
 'mobileone_s4']

